name: chimap_actual
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:

    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.6
  firebase_core: ^1.11.0
  syncfusion_flutter_datepicker: ^18.4.31-beta

  sms_autofill: ^2.2.0
  http: ^0.13.4
  fluttertoast: ^8.0.8
  firebase_storage: ^10.2.7
  rxdart: ^0.27.3
  flutter_tts: ^3.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - asset/images/muyaho.jpg
    - asset/images/homeimage.png
    - asset/images/partner.png
    - asset/images/subject.png
    - asset/images/user.png
    - asset/images/calenderIcon.png
    - asset/images/elder.png
    - asset/images/person.png
    - asset/images/lock.png
    - asset/images/girl.png
    - asset/images/question.png
    - asset/images/check.png
    - asset/images/lockChecked.png
    - asset/images/clock.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: binggrae
       fonts:
         - asset: asset/fonts/Binggrae.ttf

     - family: ROKA
       fonts:
         - asset: asset/fonts/강한육군체TTF/강한육군 Bold.ttf
           weight: 700
         - asset: asset/fonts/강한육군체TTF/강한육군 Medium.ttf

     - family: Cafe
       fonts:
         - asset: asset/fonts/Cafe24/Cafe24Dangdanghae.ttf
           weight: 700
         - asset: asset/fonts/Cafe24/Cafe24Danjunghae.ttf

     - family: Daegu
       fonts:
         - asset: asset/fonts/Daegu/IM_Hyemin-Bold.ttf
           weight: 700
         - asset: asset/fonts/Daegu/IM_Hyemin-Regular.ttf

     - family: Gosan
       fonts:
         - asset: asset/fonts/Gosan/Gosanja.ttf

     - family: Gothic
       fonts:
         - asset: asset/fonts/Gothic_A1/GothicA1-Black.ttf
         - asset: asset/fonts/Gothic_A1/GothicA1-Bold.ttf
           weight: 700
         - asset: asset/fonts/Gothic_A1/GothicA1-Regular.ttf


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
